### ISSUE TITLE
Can throw ConflictApiException instead of InternalServerErrorApiException

### ISSUE THREAD

**Issue by stevefinn44** [geeklearningio/gl-dotnet-restkit#14]
at 132,133
case HttpStatusCode.InternalServerError:
   return new ConflictApiException<TTarget>(message, result);

**Comment by sandorfr** [comment]
A bit more context would help :)

**Comment by minuz** [comment]
lol the context is this...we are having an issue that a few tests are failing only on the build server. The test response is: 
``` csharp
GeekLearning.RestKit.Core.ConflictApiException`1[[Lucsan.Workbench.Client.ResponsePagedResultWorkItemListing, Lucsan.Workbench.Client, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]] : Exception of type 'GeekLearning.RestKit.Core.ConflictApiException`1[Lucsan.Workbench.Client.ResponsePagedResultWorkItemListing]' was thrown.
```

Doing a bit of investigation, he found out that the extension used on the generated client MapToException<TTarget> will return a `ConflictApiException` on `InternalServerError`.

https://github.com/geeklearningio/gl-dotnet-restkit/blob/develop/src/GeekLearning.RestKit.Core/ClientBase.cs

**Comment by sandorfr** [comment]
Ok pr welcome then :)

**Comment by minuz** [comment]
You might need to update the version on the gl-swagger-generator

**Comment by sandorfr** [comment]
the package is now published, the template is using a wildcard, so a dotnet restore on your project should update the dependency.

**Comment by minuz** [comment]
You can close this issue... :)
