### ISSUE TITLE
Change Implementation to rely on Flurl?

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-dotnet-restkit#4]
Wondering if it would be an interesting improvement to rely on Flurl rather than play plain HttpClient especially when it comes to extensibility?

@arnaudauroux @asiffermann What do you think?

**Comment by asiffermann** [comment]
Yes, it could be great!
The static configuration method would be great for customization / extensibility, and the HttpTest class could be helpful too :)

It might be a little bit touchy to implement a smart error handling and to proper manage the HttpClient lifetime, though.

**Comment by arnaudauroux** [comment]
I love their URL builder, definitively a big missing point from the standard HTTP client ;)

**Comment by asiffermann** [comment]
And maybe we should take a look at Polly too: https://github.com/App-vNext/Polly :)

**Comment by sandorfr** [comment]
@arnaudauroux Yes, urlbuilder is an issue, I'm actually ahd to embed a piece of aspnet core code in this library. That being said, url manipulation are hidden to the end user since they are generated with swagger. 

@asiffermann Polly looks fantastic, I was actually going to implement parts of this, but I think I can easily integrate this in the template and this will be really flexible. Looking into it.

**Comment by sandorfr** [comment]
Polly is now integrated :tada: . It will probably need a few improvements but I'm already using it with some success now.

Regarding Flurl after much thoughts and becoming more familiar with it and the way it uses defaultHeaders (which I hates). Plus the breaking changes between last version I decided to no pursue this path as most of what is does it covered by generation.
